DROP TABLE IF EXISTS paper_authors;
DROP TABLE IF EXISTS papers;
DROP TABLE IF EXISTS authors;

CREATE TABLE papers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug varchar(255) NOT NULL,
  title1 varchar(300) NOT NULL,
  title2 varchar(300) NOT NULL,
  description text,
  edition_number integer NOT NULL DEFAULT 0,
  published_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX index_papers_on_slug ON papers (slug);
COMMENT ON TABLE papers IS 'Paper';
COMMENT ON COLUMN papers.slug IS 'Slug';
COMMENT ON COLUMN papers.title1 IS 'Title 1';
COMMENT ON COLUMN papers.title2 IS 'Title 2';
COMMENT ON COLUMN papers.description IS 'Description';
COMMENT ON COLUMN papers.edition_number IS 'Edition number';
COMMENT ON COLUMN papers.published_at IS 'Published at';

CREATE TABLE authors (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(110) NOT NULL,
  age integer NOT NULL,
  created_at timestamp,
  updated_at timestamp
);
CREATE INDEX index_authors_on_created_at ON authors (created_at);

CREATE TABLE paper_authors (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  paper_id integer NOT NULL,
  author_id integer NOT NULL,
  CONSTRAINT paper_authors_author_id_fk FOREIGN KEY (author_id) REFERENCES authors (id),
  CONSTRAINT paper_authors_paper_id_fk FOREIGN KEY (paper_id) REFERENCES papers (id)
);
COMMENT ON TABLE paper_authors IS 'Paper Author Relation';
COMMENT ON COLUMN paper_authors.paper_id IS 'Paper id';
COMMENT ON COLUMN paper_authors.author_id IS 'Paper author id';
