require 'spec_helper'
require 'convergence/command/dryrun'

describe 'PostgreSQL Command::Dryrun#execute' do
  def execute(dsl_path, extra_options = {})
    parse_option = {
      input: File.expand_path("#{File.dirname(__FILE__)}/../fixtures/postgres/#{dsl_path}")
    }.merge(extra_options)
    Convergence::Command::Dryrun.new(parse_option, config: postgres_settings).execute
  end

  describe 'change table options' do
    let(:exec_dsl) { 'change_table_comment_to_paper.schema' }

    it 'should be output alter table query' do
      result = execute(exec_dsl)
      expect(result).to be_include(%(# COMMENT ON TABLE "authors" IS 'Author Table';))
    end
  end

  describe 'add table' do
    let(:exec_dsl) { 'add_table.schema' }

    it 'should be output create table query' do
      result = execute(exec_dsl)
      expect(result).to be_include(%(#   "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,))
      expect(result).to be_include(%(# COMMENT ON TABLE "dummies" IS 'Dummy Table';))
      expect(result).to be_include(%(# COMMENT ON COLUMN "dummies"."id" IS 'Hello Convergence';))
    end
  end

  describe 'drop table' do
    let(:exec_dsl) { 'drop_table.schema' }

    it 'should be output drop table query' do
      result = execute(exec_dsl)
      expect(result).to be_include('DROP TABLE "paper_authors";')
    end
  end

  describe 'add columns' do
    let(:exec_dsl) { 'add_columns_to_paper.schema' }

    it 'should be output alter add column query' do
      result = execute(exec_dsl)
      expect(result).to be_include(%(# ALTER TABLE "papers" ADD COLUMN "subtitle" varchar DEFAULT NULL;))
    end
  end

  describe 'remove columns' do
    let(:exec_dsl) { 'remove_columns_to_paper.schema' }

    it 'should be output alter drop column query' do
      result = execute(exec_dsl)
      expect(result).to be_include(%(# ALTER TABLE "papers" DROP COLUMN "description";))
    end
  end

  describe 'change columns' do
    describe 'change comment' do
      let(:exec_dsl) { 'change_comment_columns_to_paper.schema' }

      it 'should be output alter table column query' do
        result = execute(exec_dsl)
        expect(result).to be_include(%(# COMMENT ON COLUMN "authors"."created_at" IS 'Created At';))
      end
    end
  end

  describe 'rename column' do
    let(:exec_dsl) { 'rename_column_on_paper.schema' }

    it 'should be output rename column query, not drop+add' do
      result = execute(exec_dsl)
      expect(result).to be_include(%(# ALTER TABLE "papers" RENAME COLUMN "description" TO "notes";))
      expect(result).not_to be_include('DROP COLUMN "description"')
      expect(result).not_to be_include('ADD COLUMN "notes"')
    end
  end

  describe 'rename table' do
    let(:exec_dsl) { 'rename_table.schema' }

    it 'should be output rename table query, not drop+add' do
      result = execute(exec_dsl)
      expect(result).to be_include(%(# ALTER TABLE "paper_authors" RENAME TO "paper_author_links";))
      expect(result).not_to be_include('DROP TABLE "paper_authors"')
      expect(result).not_to be_include('CREATE TABLE "paper_author_links"')
    end
  end

  describe 'drop foreign key' do
    let(:exec_dsl) { 'drop_foreign_key.schema' }

    it 'should be output drop foreign key query' do
      result = execute(exec_dsl)
      expect(result).to be_include(%(# ALTER TABLE "paper_authors" DROP CONSTRAINT "paper_authors_author_id_fk";))
      expect(result).to be_include(%(# ALTER TABLE "paper_authors" DROP CONSTRAINT "paper_authors_paper_id_fk";))
    end
  end
end
