require 'convergence/dumper'
require 'convergence/table'

class Convergence::Dumper::SqliteSchemaDumper
  DEFAULT_VALUE_PATTERN = /\A'(?<value>(?:[^']|'')*)'\z/.freeze
  # SQLite has no CONSTRAINT-name introspection pragma; the name is only
  # preserved in the original CREATE TABLE text.
  FOREIGN_KEY_NAME_PATTERN = /CONSTRAINT\s+"?(?<name>\w+)"?\s+FOREIGN KEY\s*\(\s*"?(?<column>\w+)"?\s*\)/i.freeze

  def initialize(connector)
    @connector = connector
    @tables = {}
  end

  def dump
    table_names.each do |table_name|
      table = Convergence::Table.new(table_name)
      parse_columns(table, column_definitions(table_name))
      parse_indexes(table, index_definitions(table_name))
      parse_foreign_keys(table, table_name)
      @tables[table_name] = table
    end
    @tables
  end

  private

  def db
    @connector.schema_client
  end

  def table_names
    db.execute("SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%'").map { |r| r['name'] }
  end

  def table_sql(table_name)
    row = db.execute('SELECT sql FROM sqlite_master WHERE type = ? AND name = ?', ['table', table_name]).first
    row ? row['sql'].to_s : ''
  end

  def column_definitions(table_name)
    db.execute(%(PRAGMA table_info("#{table_name}")))
  end

  def index_definitions(table_name)
    # origin 'c' is an explicitly created index (CREATE [UNIQUE] INDEX). 'pk' and
    # 'u' are auto-generated by a PRIMARY KEY/UNIQUE column constraint, already
    # represented on the column itself, so they are excluded here.
    db.execute(%(PRAGMA index_list("#{table_name}"))).select { |r| r['origin'] == 'c' }
  end

  def index_column_definitions(index_name)
    db.execute(%(PRAGMA index_info("#{index_name}")))
  end

  def foreign_key_definitions(table_name)
    db.execute(%(PRAGMA foreign_key_list("#{table_name}")))
  end

  def parse_columns(table, columns)
    pk_columns = columns.select { |c| c['pk'].to_i > 0 }
    single_integer_pk_cid = pk_columns.size == 1 ? pk_columns.first['cid'] : nil
    columns.each do |column|
      data_type, column_name, options = parse_column(column, single_integer_pk_cid)
      table.send(data_type, column_name, options)
    end
  end

  def parse_column(column, single_integer_pk_cid)
    raw_type = column['type'].to_s
    type_name = raw_type[/\A(\w+)/, 1].to_s
    column_name = column['name']
    is_auto_increment_pk = !single_integer_pk_cid.nil? && column['cid'] == single_integer_pk_cid && type_name.upcase == 'INTEGER'
    data_type = if is_auto_increment_pk
                  :int
                elsif type_name.empty?
                  :text
                else
                  type_name.downcase.to_sym
                end
    options = { null: column['notnull'].to_i.zero? }
    if is_auto_increment_pk
      # SQLite's `notnull` pragma column doesn't reflect the implicit NOT NULL
      # of an INTEGER PRIMARY KEY (rowid alias), so it must be forced here.
      options.merge!(primary_key: true, extra: 'auto_increment', null: false)
    else
      options.merge!(primary_key: true) if column['pk'].to_i > 0
      options.merge!(default: column_default_expression(data_type, column['dflt_value'])) unless column['dflt_value'].nil?
    end
    case data_type
    when :decimal
      precision, scale = raw_type.scan(/\d+/)
      options.merge!(precision: precision, scale: scale) if precision
    else
      limit = raw_type[/\((\d+)\)/, 1]
      options.merge!(limit: limit) unless limit.nil?
    end
    [data_type, column_name, options]
  end

  def column_default_expression(data_type, value)
    return -> { 'CURRENT_TIMESTAMP' } if data_type == :datetime && value.to_s.upcase == 'CURRENT_TIMESTAMP'
    match = DEFAULT_VALUE_PATTERN.match(value)
    return match[:value].gsub("''", "'") if match
    value
  end

  def parse_indexes(table, indexes)
    indexes.each do |index|
      columns = index_column_definitions(index['name']).sort_by { |c| c['seqno'].to_i }.map { |c| c['name'] }
      options = { name: index['name'], unique: index['unique'].to_i == 1 }
      table.index(columns, options)
    end
  end

  def parse_foreign_keys(table, table_name)
    foreign_key_names = table_sql(table_name).scan(FOREIGN_KEY_NAME_PATTERN).to_h { |name, column| [column, name] }
    foreign_key_definitions(table_name).group_by { |r| r['id'] }.each do |_id, rows|
      sorted_rows = rows.sort_by { |r| r['seq'].to_i }
      columns = sorted_rows.map { |r| r['from'] }
      to_table = sorted_rows.first['table']
      to_columns = sorted_rows.map { |r| r['to'] }
      key_name = foreign_key_names[columns.first] || "fk_#{table.table_name}_#{columns.join('_')}"
      options = {
        reference: to_table,
        reference_column: to_columns,
        name: key_name
      }
      table.foreign_key(columns, options)
    end
  end
end
